// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// find_feasible_sum_subsets
List find_feasible_sum_subsets(List S, int theta);
RcppExport SEXP _RashomonPartitionSets_find_feasible_sum_subsets(SEXP SSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(find_feasible_sum_subsets(S, theta));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _RashomonPartitionSets_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RashomonPartitionSets_find_feasible_sum_subsets", (DL_FUNC) &_RashomonPartitionSets_find_feasible_sum_subsets, 2},
    {"_RashomonPartitionSets_rcpp_hello_world", (DL_FUNC) &_RashomonPartitionSets_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_RashomonPartitionSets(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
