# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_feasible_sum_subsets <- function(S, theta) {
    .Call('_RashomonPartitionSets_find_feasible_sum_subsets', PACKAGE = 'RashomonPartitionSets', S, theta)
}

rcpp_hello_world <- function() {
    .Call('_RashomonPartitionSets_rcpp_hello_world', PACKAGE = 'RashomonPartitionSets')
}

